### ISSUE TITLE
Class Imbalance Problems

### ISSUE THREAD

**Issue by Freddy-2021** [learn-co-curriculum/dsc-class-imbalance-problems#1]
### Canvas Link

https://flatiron.illumidesk.com/user/fred0421/notebooks/dsc-class-imbalance-problems/index.ipynb

### Concern

I received an error when fitting the SMOTE object. The code has it as 'smote.fit_sample(X_train, y_train)'  and an error was returned.

The code works when you use smote.fit_resample(X_train, y_train) instead.  resample instead of sample

### Suggested Changes

The code works when you use smote.fit_resample(X_train, y_train) instead.  resample instead of sample

**Comment by hoffm386** [comment]
Resolved in b78642300a058957d311947dc634777a23ec21e5

Thanks for flagging!
