### ISSUE TITLE
Add SMOTENC

### ISSUE THREAD

**Issue by hoffm386** [learn-co-curriculum/dsc-class-imbalance-problems#2]
### Concern

SMOTE described as a category, but not other classes from `imblearn`

## (Optional) Proposed Solution

Add reference to [SMOTE-NC](https://imbalanced-learn.org/dev/references/generated/imblearn.over_sampling.SMOTENC.html) and possibly other classes as well

**Comment by bpurdy-ds** [comment]
Not going to worry about this, especially as we look toward v3.0. https://github.com/learn-co-curriculum/dsc-class-imbalance-problems/issues/2#issue-1169682756
